# Generated by Django 5.2.7 on 2026-01-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
