# Generated by Django 5.2.7 on 2026-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
