# Generated by Django 5.2.7 on 2026-01-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_populate_report_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
